## Exercises

In [1]:
import numpy as np

### Create arrays

- 1-dimensional array over the range 11, 14, 17, 20, ..., 50. In addition show the type, size, shape and number of dimensions of the array.

In [ ]:
arr1d = np.array(range(11, 50, 3))

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [6]:
arr1d.dtype

dtype('int64')

In [8]:
arr1d.size

13

In [9]:
arr1d.shape

(13,)

In [7]:
arr1d.ndim

1

- 2-dimensional array of boolean type with shape=(5,3) and all set to True.

In [45]:
arr2d = np.ones((5, 3), dtype = bool)
arr2d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- 2-dimensional array of shape=(9,3) of the alphabet a..z. Pad with empty string "" to fit the shape.

In [47]:
arr2d2 = np.ones((9, 3))
arr2d2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- 2-dimensional array of shape=(5,6) filled with '***'. Hint: see *numpy.full*.

In [ ]:
# ...

## Array indices

The exercises below cover array access and assignments using indices.

- Given the 2-dimensional array *arr2d* below, fetch the following elements
    - fetch single elements:  'a', 'f'
    - fetch [c,d] on axis-0
    - fetch [b,d,f] on axis-1

In [56]:
arr2d = np.array(list("abcdef")).reshape(3,2)
arr2d

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [60]:
arr2d[0, 0]

np.str_('a')

In [61]:
arr2d[2,1 ]

np.str_('f')

In [62]:
arr2d[1]

array(['c', 'd'], dtype='<U1')

In [67]:
arr2d[[0, 1, 2], 1]

array(['b', 'd', 'f'], dtype='<U1')

- Given the 3-dimensional array arr3d:
    - fetch:
        - [[19,20],[22,23]]
        - [[9,12,15],[11,14,17]]
    - swap:
        - on axis-0 the 2nd and the 3rd elements
        - the 1st and the 3rd element of all elements on axis-0
        - repeat the previous swap but now only on the 1st element of axis-0

In [77]:
arr3d = np.arange(3*3*3).reshape(3,3,3)

In [75]:
arr3d[2, 0:2, 1:3]

array([[19, 20],
       [22, 23]])

In [76]:
arr3d[1, :, [0, 2]]

array([[ 9, 12, 15],
       [11, 14, 17]])

In [81]:
arr3d[[1, 2]] = arr3d[[2, 1]]

In [85]:
arr3d[[0, 2]] = arr3d[[2,0]]

In [92]:
arr3d[0, [0, 2]] = arr3d[0, [2, 0]]
arr3d

array([[[ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

- Implement the function *identity(n)* that generates the identity matrix of size *n*.

In [101]:
def identity(n):
    """
    :param n:
    :return: identity matrix of size n
    """
    return np.eye(n)

In [102]:
print(identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


- 3-dimensional array of shape=(3,2,3) of the range *0..n*. Set the odd values to -1.

In [111]:
arr3d = np.arange(0, 18).reshape(3, 2, 3)
arr3d[arr3d % 2 != 0] = -1
arr3d

array([[[ 0, -1,  2],
        [-1,  4, -1]],

       [[ 6, -1,  8],
        [-1, 10, -1]],

       [[12, -1, 14],
        [-1, 16, -1]]])

- produce the following array (ref: numpy.repeat, numpy.tile) :

 <tt> [5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7]</tt>

In [ ]:
arr1d = np.array([5, 3])
arr1d = np.repeat(arr1d, 3)

array([5, 5, 5, 3, 3, 3])

In [120]:
arr1d2 = np.array([5, 7])
arr1d2 = np.tile(arr1d2, 3)
arr1d2

array([5, 7, 5, 7, 5, 7])

In [125]:
arr1d3 = np.concatenate((arr1d, arr1d2))
arr1d3

array([5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7])

## Random generator

In [126]:
from numpy.random import default_rng
rng = default_rng(1234)

Create a 1-dimensional array of random integers, range [0,100), of size 20. Test (True or False) whether the array contains any odd integers. Finally, count the number of odd integers.

In [ ]:
arr1d = rng.integers(0,100,20) 
arr1d[arr1d % 2 != 0] = -1

(arr1d == -1).sum()     # 12 odd nrs 


np.int64(12)

## Summary

1. Create a two-dimensional array of random integers over the range [0,100) with shape (8,4).
2. Calculate the following summaries on axis=0:

    - minimum, maximum, mean and median
    - 1st and 3rd quartile.

3. Write the function *summary* which takes a 2-dimensional array as input and produces an R like summary as shone below:

```
       0              1               2               3
 Min.   :13.0   Min.   :24.00   Min.   :10.00   Min.   :11.00
 1st Qu.:42.5   1st Qu.:40.75   1st Qu.:46.00   1st Qu.:26.00
 Median :67.0   Median :76.50   Median :71.00   Median :34.50
 Mean   :60.0   Mean   :67.12   Mean   :64.75   Mean   :42.88
 3rd Qu.:81.5   3rd Qu.:93.00   3rd Qu.:95.00   3rd Qu.:61.25
 Max.   :97.0   Max.   :97.00   Max.   :98.00   Max.   :86.00
```

In [160]:
rng = default_rng(12345) 
arr2d = rng.integers(0, 100, 32).reshape(8, 4)

In [ ]:
arr2d.min(axis = 0)

array([20, 22,  7,  9])

In [153]:
arr2d.max(axis = 0)

array([98, 79, 91, 94])

In [ ]:
arr2d.mean(axis = 0)

array([54.25, 50.  , 52.25, 54.25])

In [157]:
np.mean(arr2d, axis = 0)

array([54.25, 50.  , 52.25, 54.25])

In [156]:
np.median(arr2d, axis = 0)

array([62.5, 51.5, 62.5, 50. ])

In [ ]:
np.percentile(arr2d, 25, axis =0)

array([25.  , 35.25, 19.  , 27.75])

In [159]:
np.percentile(arr2d, 75, axis =0)

array([70.75, 66.25, 79.25, 89.5 ])

In [176]:
def summary(arr2d):
    summary_stats = {}
    
    summary_stats["Min."] = np.min(arr2d, axis=0)
    summary_stats["1st Qu."] = np.percentile(arr2d, 25, axis =0)
    summary_stats["Median"] = np.median(arr2d, axis = 0)
    summary_stats["Mean"] = np.mean(arr2d, axis = 0)
    summary_stats["3rd Qu."] = np.percentile(arr2d, 75, axis = 0)
    summary_stats["Max."] = np.max(arr2d, axis = 0)

    print("Summary:")
    for stat, values in summary_stats.items():
        print(f"{stat: <10}", end=": ")
        print("  ".join([f"{val: .2f}" for val in values]))

In [177]:
rng = default_rng(12345) 
arr2d = rng.integers(0, 100, 32).reshape(8, 4)

In [178]:
summary(arr2d)

Summary:
Min.      :  20.00   22.00   7.00   9.00
1st Qu.   :  25.00   35.25   19.00   27.75
Median    :  62.50   51.50   62.50   50.00
Mean      :  54.25   50.00   52.25   54.25
3rd Qu.   :  70.75   66.25   79.25   89.50
Max.      :  98.00   79.00   91.00   94.00


## Matrix multiplication

Implement function *mat_mult* which takes two 2-dimensional arrays and produces their product. Compare your results with the NumPy built-in operator '@'. Make sure that the function raises and exception if the matrix dimensions are incompatible.

In [185]:
def mat_mul(m1,m2):
    """
    Carry out matrix multiplication on m1 and m2. Raise error if the m1 and m2 are
    not compatible for multiplication.

    :param m1: 2-dimensional array
    :param m2: 2-dimensional array
    :return: m1 multiplied by m2
    """
    return

In [186]:
import numpy as np

def mat_mul(m1, m2):
    """
    Carry out matrix multiplication on m1 and m2. Raise error if the m1 and m2 are
    not compatible for multiplication.

    :param m1: 2-dimensional array
    :param m2: 2-dimensional array
    :return: m1 multiplied by m2
    """
    # Check if the number of columns of m1 is equal to the number of rows of m2
    if m1.shape[1] != m2.shape[0]:
        raise ValueError("Incompatible dimensions for matrix multiplication")
    
    # Initialize the result matrix with zeros
    result = np.zeros((m1.shape[0], m2.shape[1]))
    
    # Perform matrix multiplication
    for i in range(m1.shape[0]):  # Iterate over rows of m1
        for j in range(m2.shape[1]):  # Iterate over columns of m2
            # Perform dot product of i-th row of m1 and j-th column of m2
            result[i, j] = np.dot(m1[i, :], m2[:, j])
    
    return result

# Example usage:
m1 = np.array([[1, 2], [3, 4]])  # 2x2 matrix
m2 = np.array([[5, 6], [7, 8]])  # 2x2 matrix

# Matrix multiplication using the custom function
result = mat_mul(m1, m2)

# Compare with NumPy's built-in @ operator (matrix multiplication)
result_numpy = m1 @ m2

print("Result using custom mat_mul function:\n", result)
print("\nResult using NumPy's @ operator:\n", result_numpy)


Result using custom mat_mul function:
 [[19. 22.]
 [43. 50.]]

Result using NumPy's @ operator:
 [[19 22]
 [43 50]]


## Covariance matrix

Calculate the covariance matrix between two or more random variables:

**Synopsis:** <tt>cov(x_1,...,x_n)</tt>
   - input: x_1,..,x_n random variables
   - return: nxn symmetric array

The covariance $cov(X,Y) = E[XY] - E[X]E[Y]$.

**Data** We first generate the random variables X and Y with from a joint normal distribution given the means and covariance matrix. This can be done with *.random.multivariate_normal*:

In [183]:
cov = np.array([[1.5, .6], [ .6, .5]])  # covariance matrix
X, Y = rng.multivariate_normal(mean=(0,0), cov=cov, size=5000).T # sample 5000


Here is the scatter plot of our data:

In [184]:
import matplotlib.pyplot as plt
plt.scatter(X, Y, alpha=.5, s=.5);

ModuleNotFoundError: No module named 'matplotlib'

In [187]:
np.cov(X, Y)

array([[1.48832587, 0.6043004 ],
       [0.6043004 , 0.50507387]])

Implement the function cov and compare the results with NumPy built-in function *np.cov*.

In [ ]:
# *args represents set of arguments and is iterable. calls will look
# like: cov(x), cov(x,y), cov(x,y,z), etc.
#
def cov(*args):
    """

    :param args:
    :return:
    """