## Exercises

In [3]:
import numpy as np

### Create arrays

- 1-dimensional array over the range 11, 14, 17, 20, ..., 50. In addition show the type, size, shape and number of dimensions of the array.

- 2-dimensional array of boolean type with shape=(5,3) and all set to True.

- 2-dimensional array of shape=(9,3) of the alphabet a..z. Pad with empty string "" to fit the shape.

- 2-dimensional array of shape=(5,6) filled with '***'. Hint: see *numpy.full*.

In [10]:
arr1 = np.array([range(11, 51, 3)])
arr1.dtype, arr1.shape, arr1.size, arr1.ndim

(dtype('int64'), (1, 14), 14, 2)

In [15]:
np.zeros((5,3),dtype=bool) # OR: 
~ np.ones((5,3), dtype=bool) 

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [19]:
arr2 = np.array(list("abcdefghijklmnopqrstuvwxyz")+[""]).reshape(9,3)
arr2

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i'],
       ['j', 'k', 'l'],
       ['m', 'n', 'o'],
       ['p', 'q', 'r'],
       ['s', 't', 'u'],
       ['v', 'w', 'x'],
       ['y', 'z', '']], dtype='<U1')

## Array indices

The exercises below cover array access and assignments using indices.

- Given the 2-dimensional array *arr2d* below, fetch the following elements fetch:
    - single elements:  'e', 'g'
    - [e,f]
    - [h,e,b]
    - [h,i]
    - [d,b,f,h]

In [4]:
arr2d = np.array(list("abcdefghi")).reshape(3,3)
arr2d

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [47]:
arr2d[1, 1], arr2d[1, 2]
arr2d[1, 1:]
arr2d[:,1][::-1]
arr2d[2, 1:]
arr2d[[1,0,1,2],[0,1,2,1]] 

array(['d', 'b', 'f', 'h'], dtype='<U1')

In [5]:
arr2d[:,1][::-1]

array(['h', 'e', 'b'], dtype='<U1')

- Given the 3-dimensional array arr3d:
    - fetch:
        - [[19,20],[22,23]]
        - [[9,12,15],[11,14,17]]
    - swap:
        - on axis-0 the 2nd and the 3rd elements
        - the 1st and the 3rd element of all elements on axis-0
        - repeat the previous swap but now only on the 1st element of axis-0

In [53]:
arr3d = np.arange(3*3*3).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
arr3d[2, :2:, 1:]
arr3d[1, 0:, 0]
arr3d[1, 0:, 2]
arr3d[1,:,[0,2]]

array([[ 9, 12, 15],
       [11, 14, 17]])

In [69]:
arr3d.swapaxes(0, 1)
arr3d[[0,2,1]]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

- Implement the function *identity(n)* that generates the identity matrix of size *n*.

- 3-dimensional array of shape=(3,2,3) of the range *0..n*. Set the odd values to -1.

In [74]:
arr3d = np.arange(3*3*3).reshape(3,3,3)
arr_copy = arr3d.copy()

arr_copy[arr3d % 2 != 0] = -1
arr_copy

array([[[ 0, -1,  2],
        [-1,  4, -1],
        [ 6, -1,  8]],

       [[-1, 10, -1],
        [12, -1, 14],
        [-1, 16, -1]],

       [[18, -1, 20],
        [-1, 22, -1],
        [24, -1, 26]]])

- produce the following array (ref: numpy.repeat, numpy.tile) :

 <tt> [5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7]</tt>

In [87]:
arr1 = np.repeat([5, 3], 3)
arr2 = np.tile([5,7], 3)

np.concatenate((np.repeat([5, 3], 3), np.tile([5,7], 3)))

array([5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7])

- Create a (8,8) two-dimensional array to represent a chessboard filled with 0 and 1 representing black and white squares respectively. Make sure the orientation is correct with leading diagonal set to white.

In [ ]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

- Implement the function `grid_x(n)` based on the description below. Make use of numpy functions and vectorisation capability to avoid looping.

In [121]:
def grid_x(n):
    """
    Generates a 2D grid of specified size (n x n) with an 'X' shape pattern
    represented by "#" symbols. All other cells in the grid are represented
    by ".".

    Parameters
    ----------
    n : int
        The size of the grid. Must be a positive integer.

    Returns
    -------
    (n x n) numpy.ndarray containing the X pattern.

    """
    
    cond = (np.identity(n,dtype="?") | np.flip(np.identity(n, dtype="?"),axis=1))
    return np.where(cond,"#",".")

## Random generator

Create a 1-dimensional array of random integers, range [0,100), of size 20. Test (True or False) whether the array contains any odd integers. Finally, count the number of odd integers.

In [149]:
rng = np.random.default_rng(222)
int_arr = rng.integers(0, 100, 20)
(int_arr % 2 != 0).any()
(int_arr % 2 != 0).sum() # 11 

np.int64(11)


## Summary

1. Create a two-dimensional array of random integers over the range [0,100) with shape (8,4).
2. Calculate the following summaries on axis=0:

    - minimum, maximum, mean and median
    - 1st and 3rd quartile.

3. Write the function *summary* which takes a 2-dimensional array as input and produces an R like summary as shone below:

```
       0              1               2               3
 Min.   :13.0   Min.   :24.00   Min.   :10.00   Min.   :11.00
 1st Qu.:42.5   1st Qu.:40.75   1st Qu.:46.00   1st Qu.:26.00
 Median :67.0   Median :76.50   Median :71.00   Median :34.50
 Mean   :60.0   Mean   :67.12   Mean   :64.75   Mean   :42.88
 3rd Qu.:81.5   3rd Qu.:93.00   3rd Qu.:95.00   3rd Qu.:61.25
 Max.   :97.0   Max.   :97.00   Max.   :98.00   Max.   :86.00
```

In [ ]:
rng = np.random.default_rng(222)
arr = rng.integers(0, 100, 32).reshape(8,4)

max = np.max(arr, axis=0)
min = np.min(arr, 0)
mean = np.mean(arr,0)
median = np.median(arr,0)
first_qrt = np.quantile(arr, 0.25, 0)
third_qrt = np.quantile(arr, 0.75, 0)

In [172]:
def summary(x):
    if x.ndim == 2:
        aggregates = np.stack( [np.min(x,axis=0),              # minimum
                                np.quantile(x, 0.25, axis=0),  # 1st quartile
                                np.median(x,axis=0),           # 2nd quartile
                                np.mean(x,axis=0),             # mean
                                np.quantile(x, 0.75, axis=0),  # 3rd quartile
                                np.max(x,axis=0)],             # maximum
                               axis=0)

        return aggregates
    else:
        raise Exception("Only 2-dimensional arrays are supported !")
    
summary(x=arr)

array([[ 1.   , 36.   ,  2.   ,  8.   ],
       [36.75 , 37.75 , 26.75 ,  8.75 ],
       [54.5  , 51.   , 38.   , 50.   ],
       [46.875, 53.625, 43.375, 42.625],
       [62.5  , 59.25 , 60.25 , 62.5  ],
       [72.   , 89.   , 83.   , 86.   ]])

## Matrix multiplication

Implement function *mat_mult* which takes two 2-dimensional arrays and produces their product. Compare your results with the NumPy built-in operator '@'. Make sure that the function raises and exception if the matrix dimensions are incompatible.

In [150]:
a = rng.integers(0, 10, 6).reshape(3, 2)
b = rng.integers(0, 10, 6).reshape(2, 3)

In [152]:
def mat_mul(m1,m2):
    """
    Use broadcast to speed up.
    :param m1:
    :param m2:
    :return: matrix m1 multiplied by  m2
    """
    if m1.shape[1]==m2.shape[0]:
        return np.array([np.sum(x * m2.T, axis=1) for x in np.split(m1,m1.shape[0])])
    else:
        raise Exception("incompatible dimensions !")

## Covariance matrix

Calculate the covariance matrix between two or more random variables:

**Synopsis:** <tt>cov(x_1,...,x_n)</tt>
   - input: x_1,..,x_n random variables
   - return: nxn symmetric array

The covariance $cov(X,Y) = E[XY] - E[X]E[Y]$.

**Data** We first generate the random variables X and Y with from a joint normal distribution given the means and covariance matrix. This can be done with *.random.multivariate_normal*:

Here is the scatter plot of our data:

Implement the function cov and compare the results with NumPy built-in function *np.cov*.