## Exercises

In [19]:
import numpy as np

### Create arrays

- 1-dimensional array over the range 11, 14, 17, 20, ..., 50. In addition show the type, size, shape and number of dimensions of the array.


In [20]:
arr1d = np.arange(11, 51, 3)
arr1d.dtype,arr1d.size, arr1d.shape, arr1d.ndim

(dtype('int64'), 14, (14,), 1)

- 2-dimensional array of boolean type with shape=(5,3) and all set to False.

In [21]:
# 0 => False
np.zeros((5,3),dtype=bool)
# ~ (1 => True) => False
~np.ones((5,3),dtype=bool)


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

- 2-dimensional array of shape=(9,3) of the alphabet a..z.

In [22]:
# You'll need to pad the list to fit the shape.
np.array(list('abcdefghijklmnopqrstuvwxyz') + [""]).reshape(9,3)

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i'],
       ['j', 'k', 'l'],
       ['m', 'n', 'o'],
       ['p', 'q', 'r'],
       ['s', 't', 'u'],
       ['v', 'w', 'x'],
       ['y', 'z', '']], dtype='<U1')


- The two 3-dimensional arrays are filled with identical data but different orders. Without running the code predict the layout of the array.

In [23]:
arr_c = np.array([ 5,  9, 16, 12,  3, 14, 11, 13]).reshape((2,2,2), order='C')
arr_f = np.array([ 5,  9, 16, 12,  3, 14, 11, 13]).reshape((2,2,2), order='F')
arr_f

array([[[ 5,  3],
        [16, 11]],

       [[ 9, 14],
        [12, 13]]])

`order='C'`:

```
[...]
```

`order='F'`:

```
[...]
```

## Array indices

The exercises below cover array *access* and *assignments* using indices and slices.

- Given the 2-dimensional array *arr2d* below, fetch the following elements fetch:
    - single elements:  'e', 'g'
    - [e,f]
    - [h,e,b]
    - [h,i]
    - [d,b,f,h]

In [24]:
arr2d = np.array(list("abcdefghi")).reshape(3,3)
arr2d[1,1], arr2d[2,0]
arr2d[1,1:]
arr2d[:,1][::-1]
arr2d[-1,1:]
arr2d[[1,0,1,2],[0,1,2,1]]

array(['d', 'b', 'f', 'h'], dtype='<U1')

- Given the 3-dimensional array arr3d:
    - fetch:
        - [[19,20],[22,23]]
        - [[9,12,15],[11,14,17]]
    - swap
        - on axis-0 the 2nd and the 3rd elements
        - the 1st and the 3rd element of all elements on axis-0
        - repeat the previous swap but now only on the 1st element of axis-0

In [25]:
arr3d = np.arange(3*3*3).reshape(3,3,3)
#
arr3d[2,:2,1:]
#
arr3d[1,:,[0,2]]
#
np.stack([arr3d[1,:,i] for i in [0,2]])
#
arr3d[[0,2,1]]
# alternatively
# arr3d[:,[2,1,0],:]
#
np.stack([arr3d[0], arr3d[1,[2,1,0],:], arr3d[2]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[15, 16, 17],
        [12, 13, 14],
        [ 9, 10, 11]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

- Make a copy of `arr3d` from previous exercise and set its odd values to -1.

In [26]:
arr3d_copy = arr3d.copy()
arr3d_copy[arr3d % 2 != 0] = -1
arr3d_copy

array([[[ 0, -1,  2],
        [-1,  4, -1],
        [ 6, -1,  8]],

       [[-1, 10, -1],
        [12, -1, 14],
        [-1, 16, -1]],

       [[18, -1, 20],
        [-1, 22, -1],
        [24, -1, 26]]])

- Implement the function *identity_(n)* that generates the identity matrix of size *n*. You can check you results with the build-in `numpy.identity` function.

In [27]:
def identity_(n):
    """
    Generate an identity matrix of size n x n.

    Returns:
        (n x n) ndarray
    """
    im = np.zeros((n,n))
    im[np.arange(n),np.arange(n)] = 1
    return im

- Create the array [5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7] (ref: numpy.repeat, numpy.tile):

In [28]:
np.concatenate((np.repeat([5,3],3), np.tile([5,7],3)))

array([5, 5, 5, 3, 3, 3, 5, 7, 5, 7, 5, 7])

- Create a (8,8) two-dimensional array to represent a chessboard filled with 0 and 1 representing black and white squares respectively. Make sure the orientation is correct with leading diagonal set to white.

In [29]:
# Possible solutions
#
# (1) np.tile
np.tile(np.array([[1,0],[0,1]] ),(4,4))
# (2) np.repeat
row = np.repeat(np.array([[0, 1]]),4, axis=0).flatten()
np.array([row[::-1] if i%2==0 else row for i in range(8)])
# (3) ???

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

- Implement the function `grid_x(n)` based on the description below. Make use of numpy functions and vectorisation capability to avoid looping.

In [30]:
def grid_x(n):
    """
    Generates a 2D grid of specified size (n x n) with an 'X' shape pattern
    represented by "#" symbols. All other cells in the grid are represented
    by ".".

    Parameters
    ----------
    n : int
        The size of the grid. Must be a positive integer.

    Returns
    -------
    (n x n) numpy.ndarray containing the X pattern.

    """
    cond = (np.identity(5,dtype="?") | np.flip(np.identity(5, dtype="?"),axis=1))
    return np.where(cond,"#",".")

## Tic-tac-toe

Tic-tac-toe is a classic two-player game played on a 3x3 grid. Players take turns marking empty squares, one with an "X" and the other with an "O". The objective is to be the first to form a horizontal, vertical, or diagonal line of three consecutive marks. If all squares are filled without achieving this, the game ends in a draw.


- Implement the class TicTacToe with a method `play`. It is an interactive game, a possible scenario:

```
ttt = TicTacToe() # TicTacToe instance 'ttt'
[out]
0 | 0 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
Player 1's turn:

ttt.play((0,0)) # player 1
[out]
1 | 0 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
Player 2's turn:

ttt.play((0,1)) # player 2
[out]
1 | 2 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
Player 1's turn:

...
...

Player 1's turn:
1 | 2 | 2
---------
0 | 1 | 0
---------
0 | 0 | 1
Winner is player 1
```

- Upgrade the class to enable playing against the computer, a random move will suffice.


In [31]:

class TicTacToe:
    """
    A class representing a Tic Tac Toe game.

    This class provides functionality to play a game of Tic Tac Toe, including board management,
    player turn alternation, move validation, winner determination, and the ability to reset the
    game. The board is a 3x3 grid represented as a NumPy array, and the game can be played
    interactively between two players. There is also an option to make random moves programmatically.
    """

    def __init__(self, quiet=False):
        self.board = np.zeros((3,3), dtype=int)
        self.turn = self._alternate()
        self.player = next(self.turn) # player 1 starts
        self.winner = None
        self.moves = 0
        self.quiet = quiet

        if not self.quiet:
            self.display()

    @staticmethod
    def _alternate():
        """
        This static method is a generator that alternates between the values 1 and 2 indefinitely. It
        starts with 1, and each subsequent 'next' call to the generator will yield the next alternating value.

        Returns:
            A generator that yields alternating integers 1 and 2.
        """

        while True:
            yield 1
            yield 2

    def display(self):
        """
        This method displays the current state of the game board, including all moves
        made so far. It specifies how many moves have been made and which player has
        just taken their turn. The board is presented in a formatted grid layout,
        with rows separated by horizontal lines for better readability.

        Example:

            Current state of the board after 4 moves, player 2 has just played:
            1 | 0 | 0
            ---------
            0 | 1 | 2
            ---------
            0 | 2 | 0

        """

        r_ = [" | ".join(map(str, row)) for row in self.board]
        hl = "\n" + "-" * len(r_[0]) + "\n"
        print(hl.join(r_))

    def play(self, position: tuple[int, int]):
        """
        Updates the game state with a new move at the given position.

        The function performs checks to ensure the game is ongoing and the specified
        move is valid. Based on the move's outcome, it updates the board, switches the
        current player, evaluates for a winner, and displays the newly updated game
        state.

        Parameters:
            position (tuple[int, int]): A tuple containing the row and column indices
            of the board where the move is being made.

        Raises:
            Warning: If the specified move is invalid, such as choosing an occupied
            cell or a position out of range.
        """


        row, col = position
        if self.winner is not None:
            print("Game already over, reset the game to play again !")
        elif row < 3 or col < 3:
            if self.board[row, col] == 0:
                self.board[row, col] = self.player
                self.moves += 1
                self.player = next(self.turn)
                if not self.quiet:
                    self.display()
                if self.check():
                    if not self.quiet:
                        print(f"Winner is player {self.winner}")
                elif self.winner is None and self.moves == 9:
                    self.winner = 0
                    if not self.quiet:
                        print("Draw")
                else:
                    pass
            else:
                print("Invalid move, choose an empty cell !")
        else:
            print("Invalid move, choose a position in range !")

    def check(self):
        """
        Check if there is a winner in the game.

        This method determines if there is a winner by checking rows, columns, and
        diagonals for a consistent value representing a player.

        The method iterates over each player (-1 and 1) and examines all rows, columns,
        and both diagonals of the board to look for a winning sequence. When a winner
        is found, the corresponding player is set as the winner, and the method exits
        immediately with True. If no winner is detected, the method returns False.

        Returns
        -------
        bool
            True if a player has won, False otherwise.
        """
        for player in [1, 2]:
            for i in range(3):
                if np.all(self.board[i, :] == player) or np.all(self.board[:, i] == player):
                    self.winner = player
                    return True
            if np.all(self.board.diagonal() == player) or np.all(np.fliplr(self.board).diagonal() == player):
                self.winner = player
                return True
        print(f"Player {self.player}'s turn:")
        return False

    def computer(self):
        """
        Randomly selects an empty position on the board and updates it with a move.
        Raises an exception if no positions are available.

        Raises:
            Exception: If there are no empty positions left on the board.
        """
        pos = np.argwhere(self.board == 0)
        if pos.size > 0:
            row, col = pos[np.random.choice(pos.shape[0]), :]
            self.play((row, col))
        else:
            raise Exception("No possible moves on the board !")

    def reset(self):
        self.board = np.zeros((3,3), dtype=int)
        self.turn = self._alternate()
        self.player = next(self.turn) # player 1 starts
        self.winner = None
        self.moves = 0

    def sim(self):
        self.reset()
        for i in range(9):
            self.computer()
        return self.winner


np.random.seed(42)
ttt = TicTacToe() # TicTacToe instance 'ttt'
ttt.play((0,0)) # player 1
ttt.play((0,1)) # player 2
ttt.play((1,1)) # player 1
ttt.play((0,2)) # player 2
ttt.play((2,2)) # player 1

0 | 0 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
1 | 0 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
Player 2's turn:
1 | 2 | 0
---------
0 | 0 | 0
---------
0 | 0 | 0
Player 1's turn:
1 | 2 | 0
---------
0 | 1 | 0
---------
0 | 0 | 0
Player 2's turn:
1 | 2 | 2
---------
0 | 1 | 0
---------
0 | 0 | 0
Player 1's turn:
1 | 2 | 2
---------
0 | 1 | 0
---------
0 | 0 | 1
Winner is player 1


## Random generator

In [32]:
from numpy.random import default_rng
rng = default_rng(12345)

- Create a 1-dimensional array of random integers, range [0,100), of size 20. Test (True or False) whether the array contains any odd integers. Finally, count the number of odd integers.

In [33]:
arr1d = rng.integers(100, size=20)  # 20 random integers out of [0,100)
(arr1d % 2 != 0).any()              # any odd integer?
(arr1d % 2 == 0).sum()              # count of even integers
arr1d

array([69, 22, 78, 31, 20, 79, 64, 67, 98, 39, 83, 33, 56, 59, 21, 18, 22,
       67, 61, 94])

## Summary

1. Create a two-dimensional array of random integers over the range [0,100) with shape (8,4).
2. Calculate the following summaries on axis=0:

    - minimum, maximum, mean and median
    - 1st and 3rd quartile.

3. Write the function *summary* which takes a 2-dimensional array as input and produces an R like summary as shown below:

```
       0              1               2               3
 Min.   :13.0   Min.   :24.00   Min.   :10.00   Min.   :11.00
 1st Qu.:42.5   1st Qu.:40.75   1st Qu.:46.00   1st Qu.:26.00
 Median :67.0   Median :76.50   Median :71.00   Median :34.50
 Mean   :60.0   Mean   :67.12   Mean   :64.75   Mean   :42.88
 3rd Qu.:81.5   3rd Qu.:93.00   3rd Qu.:95.00   3rd Qu.:61.25
 Max.   :97.0   Max.   :97.00   Max.   :98.00   Max.   :86.00
```

In [34]:
# 1)
arr2d = rng.integers(0,100,size=(8,4))
# 2)
np.min(arr2d,axis=0)
np.max(arr2d,axis=0)
np.mean(arr2d,axis=0)
np.median(arr2d,axis=0)
np.quantile(arr2d,0.25, axis=0)
np.quantile(arr2d,0.75, axis=0)

array([71.5 , 66.75, 60.5 , 82.75])

In [17]:
# Solutions 1
# Here only the NumPy aggregate functions part is implemented and the data is returned
# as NumPy array.

def summary(x):
    """
    Report a summary for each variable (column) in the 2-dimensional array. The summary includes
    minimum, first quartile, median, mean, third quartile and maximum.

    :param x: 2-dimensional array
    :return: 2-dimensional array of summaries per aggregate
    """
    if x.ndim == 2:
        aggregates = np.stack( [np.min(x,axis=0),              # minimum
                                np.quantile(x, 0.25, axis=0),  # 1st quartile
                                np.median(x,axis=0),           # 2nd quartile
                                np.mean(x,axis=0),             # mean
                                np.quantile(x, 0.75, axis=0),  # 3rd quartile
                                np.max(x,axis=0)],             # maximum
                               axis=0)

        return aggregates
    else:
        raise Exception("Only 2-dimensional arrays are supported !")

In [ ]:
# Solutions 2
# Here the summaries are calculated and the results are formatted and printed on screen.
#
import math

def summary(x):
    """
    Report a summary for each variable (column) in the 2-dimensional array. The summary includes
    minimum, first quartile, median, mean, third quartile and maximum.

    :param x: 2-dimensional array
    :return: None
    """
    if x.ndim == 2:
        tags = ["Min.   ", "1st Qu.", "Median ", "Mean   ", "3rd Qu.", "Max.   "]
        aggregates = np.stack( [np.min(x,axis=0),              # minimum
                                np.quantile(x, 0.25, axis=0),  # 1st quartile
                                np.median(x,axis=0),           # 2nd quartile
                                np.mean(x,axis=0),             # mean
                                np.quantile(x, 0.75, axis=0),  # 3rd quartile
                                np.max(x,axis=0)],             # maximum
                               axis=0)
        """
        Format the output.
        ------------------

        Printing multiple variables (columns) side by side requires that they fit inside the the line width
        of the output cell. Therefore with more variables you'll need to introduces steps and print per step
        a  fixed set  of columns.
        """

        size = x.shape[1]                                           # number of variables (columns)
        decimal_part = 3
        num_widths = [                                              # number widths of all columns
                       len(str(round(max(aggregates[:,i])))) +      # maximum width aggregate values
                       decimal_part                                 # decimal part width ".00"
                       for i in range(aggregates.shape[0])]
        line_width = np.get_printoptions()["linewidth"]             # line width to fit output
        gap = 5                                                     # space between column summaries
        label_width = len("Min.  :")                                # label width
        step = line_width // (label_width + gap + max(num_widths))  # number of variables to print per row

        for row in range(math.ceil(size/step)):
            header = [s for s in np.arange(row*step,min(row*step + step,size) ).astype("str")]
            for tid in range(len(tags)):
                line = [f"{tags[tid]}: " +  (f"{aggregates[tid,i]:.2f}".rjust(num_widths[tid]))
                        for i in range(row*step, min(row*step + step,size) )]
                if tid==0:
                    print((" "*gap).join([str(header[i]).center(len(line[i])) for i in range(len(line))]))
                print( (" " * gap).join(line) )
    else:
        raise Exception("Only 2-dimensional arrays are supported !")

## Matrix multiplication

Implement the function *mat_mult* which takes two 2-dimensional arrays and produces their product. Compare your results with the NumPy built-in operator '@'. Make sure that the function raises an exception if the matrix dimensions are incompatible.

In [35]:
a = rng.integers(0,10,6).reshape(3,2)
b = rng.integers(0,10,6).reshape(2,3)

In [36]:
def mat_mul(m1,m2):
    """
    Use broadcast to speed up.
    :param m1:
    :param m2:
    :return: matrix m1 multiplied by  m2
    """
    if m1.shape[1]==m2.shape[0]:
        return np.array([np.sum(x * m2.T, axis=1) for x in np.split(m1,m1.shape[0])])
    else:
        raise Exception("incompatible dimensions !")

m1 = rng.integers(0,100,size=(5,7))
m2 = rng.integers(0,100,size=(7,10))
np.array_equal(mat_mul(m1,m2),  m1 @ m2)

True

In [97]:
%timeit mat_mul(m1,m2)

15.1 μs ± 260 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [98]:
# built-in matrix multiplication
%timeit m1 @ m2

611 ns ± 5.27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
